### ISSUE TITLE
Request status (Input source, current app etc.)

### ISSUE THREAD

**Issue by Alpoy** [supersaiyanmode/PyWebOSTV#17] opened 2018-12-07 18:26 UTC
Hi,

Is it possible to request a feature to poll current status like current input source or current active app etc.? or is it possible already ? :-)

**Comment by supersaiyanmode** [comment] 2018-12-07 18:37
I just re-read the source -- and was surprised it doesn't feature it. It should be straightforward to implement. I guess I will add it by mid next week. Thanks for creating this issue. :)

**Comment by supersaiyanmode** [comment] 2018-12-14 13:21
Done in the develop branch. I'd really appreciate if you could test it out.

Current Active App: `ApplicationControl(client).get_current()` -> `"applicationIdOfForegroundApp"`. You can get the full app info getting the `Application` instance from  `.list_apps()`.

As for current source, just call the above API. AFAICT input sources are, in a way, applications.

**Comment by Gustry** [comment] 2018-12-14 13:50
Thanks for this addition. It will be useful.
I think you didn't update the readme about your new command.

**Comment by supersaiyanmode** [comment] 2018-12-15 06:56
Hi @Gustry The develop branch has quite a few clean ups (and a few API changes which shouldn't be noticeable directly). Updating the README might not be super trivial. But I'll do it soon.

**Comment by Alpoy** [comment] 2018-12-17 19:04
I'm sorry, I'm having some trouble figuring out how to launch an app. Could you give an example on how to launch Netflix? 

like: app.launch("Netflix") ....

**Comment by Alpoy** [comment] 2018-12-17 19:34
Thanks for helping and sorry for going offtopic but that only gives me this:
print(apps) gives a list with:
[<Application 'Live TV'>, <Application 'Netflix'>,

so I tried:
app.launch(apps['Netlix'])
Which returns:
TypeError: list indices must be integers, not str 

Seems I have to loop the apps, figure which is "netflix" and pass the index (int) of netflix in the "apps" list....

**Comment by kilian579** [comment] 2018-12-17 19:39
Oh sry I forgot you needed the list id:

i=0
for a in apps:
    print(i, a)
    i+=1


Should do the job

**Comment by Gustry** [comment] 2018-12-17 21:14
Small tip @kilian579 to have an auto incremented variable, it's more pythonic ;-)

```python
for i, a in enumerate(apps):
    print(i, a)
```

**Comment by supersaiyanmode** [comment] 2018-12-19 04:32
I have updated the README.md file with info on new APIs (in the develop branch). Please take a look and let me know if its not clear. Thanks a lot, all of you!

(I have also added examples on launching Youtube, netflix etc seeing as it wasn't super clear earlier.. :))

PS: I'd really appreciate if you can test it out (especially subscription APIs). I am hoping to get this tested before I merge to master.

**Comment by kilian579** [comment] 2018-12-20 12:01
### My Test Results:

_New Functions:_
   -   `app.get_current()` works well
   -   `print(foreground_app = [x for x in apps if app_id == x["id"]][0])` works well
   -   `print(icon_url)` works well
   -   `inp.dash()` which seems to be the OK button works well

_Subscriptions:_
   -   `media.subscribe_get_volume(self._on_volume_change)`: works as intended
   -   `app.subscribe_get_current(self._on_app_change)`:  works as intended

/~~~
### Little Test Sheet:
It will print out all of your apps and you can control your TV intuitively via command line. Also, it will write all your apps + ids into _"APP_ID.txt"_


```
from pywebostv.discovery import *
from pywebostv.connection import *
from pywebostv.controls import *
from time import sleep

ip="your ip"

store = {}

client = WebOSClient(ip)
client.connect()
for status in client.register(store):
    if status == WebOSClient.PROMPTED:
        print("Please accept the connect on the TV!")
    elif status == WebOSClient.REGISTERED:
        print("Registration successful!")
        print("STORE", store)


def scan_apps(client: WebOSClient,file_id="APP_ID.txt"):
    ###Saves ID +" "+ App Name to file_id; One Line per App###
    app = ApplicationControl(client)
    apps=app.list_apps()
    open(file_id,'w').close() #clear old file
    file=open(file_id,'w')
    for i, x in enumerate(apps):
        app_name=str(x)[14:-2]
        line=app_name+" "+str(i)+"\n"
        print(app_name)
        file.write(line)
    file.close()


def controlPrompt(client):
    """ type 'exit' to stop"""
    inp = InputControl(client)
    tv_control = TvControl(client)
    media = MediaControl(client)
    system = SystemControl(client)
    app = ApplicationControl(client)
    apps = app.list_apps()

    scan_apps(client)

    inp.connect_input()
    controls=input("Execute:" ).split()
    control=controls[0]
    while not control == "exit":

        if control == "CLICK":
            inp.click()
        elif control == "OK":
            inp.dash()
        elif control == "UP":
            inp.up()
        elif control == "DOWN":
            inp.down()
        elif control == "LEFT":
            inp.left()
        elif control == "RIGHT":
            inp.right()
        elif control == "HOME":
            inp.home()
        elif control == "BACK":
            inp.back()
        elif control == "ENTER":
            inp.enter()
        elif control == "MOVE":
            inp.move(controls[1], controls[2])
        elif control == "CDOWN":
            tv_control.channel_down()
        elif control == "CUP":
            tv_control.channel_up()
        elif control == "VUP":
            media.volume_up()
        elif control == "VDOWN":
            media.volume_down()
        elif control == "GETVOLUME":
            media.get_volume()
        elif control == "PLAY":
            media.play()
        elif control == "PAUSE":
            media.pause()
        elif control == "STOP":
            media.stop()
        elif control == "REWIND":
            media.rewind()
        elif control == "FFWD":
            media.fast_forward()
        elif control == "INFO":
            a=system.info()
            print(a)
        elif control =="NOTIFY":
            system.notify("This is a notification message!")
        elif control =="CURRENT":
            print(app.get_current())
        elif control=="FOREGROUND":
            app_id = app.get_current()
            print([x for x in apps if app_id == x["id"]][0])
        elif control=="ICON":
            app_id = app.get_current()
            foreground_app=[x for x in apps if app_id == x["id"]][0]
            icon_url = foreground_app["icon"]
            print(icon_url)
        elif control=="APP":
            app_req=controls[1]
            launching=None
            try:
                launching = [x for x in apps if "youtube" in x["title"].lower()][0]
            except:
                print("App",app_req, "doesnt exist.")
                pass
            if launching :
                launch_info = app.launch(launching)

        control=input("Execute:" )

        try:
            app.close(launch_info)
        except UnboundLocalError:
            pass

    inp.disconnect_input()

controlPrompt(client)
```   

Thank you @supersaiyanmode 

PS: I tested every function like 3-4 times, so I definitely haven't checked every possible case

**Comment by supersaiyanmode** [comment] 2018-12-21 04:36
This has been merged to master. Closing this issue. Thanks all! :)

**Closed by supersaiyanmode** 2018-12-21 04:36 UTC
