### ISSUE TITLE
Script requires authentication on TV every time we run the code.

### ISSUE THREAD

**Issue by thevickypedia** [supersaiyanmode/PyWebOSTV#44] opened 2020-11-11 03:46 UTC
This is more of a question? 

Is there a way we can skip that part, I have a piece of code using which I want control the TV but it seems that every time I run this code, I will have to authenticate (press Yes) on the TV screen prompt. Is that how it is or is there a way around?

**Comment by supersaiyanmode** [comment] 2020-11-11 04:08
Duplicate of https://github.com/supersaiyanmode/PyWebOSTV/issues/35.

You need to store the credentials after you're done with the registration for the first time. In the second run, provide a dictionary-like object to the register function, the function will inspect the incoming object to see if there's an existing credential, if so uses it silently without invoking authorization.

**Closed by supersaiyanmode** 2020-11-11 04:08 UTC

**Comment by supersaiyanmode** [comment] 2020-11-11 04:20
Please re-open this issue (and attach minimal, reproducible code), if you didn't follow the README or the linked issue. We want to improve it, if the instructions are not readily apparent.

**Comment by thevickypedia** [comment] 2020-11-11 16:01
> Please re-open this issue (and attach minimal, reproducible code), if you didn't follow the README or the linked issue. We want to improve it, if the instructions are not readily apparent.

Works like a charm :) Thank you so much..

**Comment by thevickypedia** [comment] 2020-11-11 16:01
> Duplicate of #35.
> 
> You need to store the credentials after you're done with the registration for the first time. In the second run, provide a dictionary-like object to the register function, the function will inspect the incoming object to see if there's an existing credential, if so uses it silently without invoking authorization.

Works like a charm :) Thank you so much..
